# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loadleveler_collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loadleveler_collector.proto',
  package='loadleveler_collector',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bloadleveler_collector.proto\x12\x15loadleveler_collector\"\xb9\x01\n\x0bJobsRequest\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x14\n\x0coutput_style\x18\x07 \x01(\t\x12\x10\n\x08post_url\x18\x08 \x01(\t\x12\x18\n\x10\x63ontent_encoding\x18\t \x01(\t\x12\x0f\n\x07verbose\x18\n \x01(\x08\"\xbb\x01\n\rQueuesRequest\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x14\n\x0coutput_style\x18\x07 \x01(\t\x12\x10\n\x08post_url\x18\x08 \x01(\t\x12\x18\n\x10\x63ontent_encoding\x18\t \x01(\t\x12\x0f\n\x07verbose\x18\n \x01(\x08\"*\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xc6\x01\n\x14LoadLevelerCollector\x12T\n\x0b\x43ollectJobs\x12\".loadleveler_collector.JobsRequest\x1a\x1f.loadleveler_collector.Response\"\x00\x12X\n\rCollectQueues\x12$.loadleveler_collector.QueuesRequest\x1a\x1f.loadleveler_collector.Response\"\x00\x62\x06proto3')
)




_JOBSREQUEST = _descriptor.Descriptor(
  name='JobsRequest',
  full_name='loadleveler_collector.JobsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='loadleveler_collector.JobsRequest.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo', full_name='loadleveler_collector.JobsRequest.repo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='loadleveler_collector.JobsRequest.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='loadleveler_collector.JobsRequest.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='loadleveler_collector.JobsRequest.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='loadleveler_collector.JobsRequest.password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_style', full_name='loadleveler_collector.JobsRequest.output_style', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_url', full_name='loadleveler_collector.JobsRequest.post_url', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_encoding', full_name='loadleveler_collector.JobsRequest.content_encoding', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='loadleveler_collector.JobsRequest.verbose', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=240,
)


_QUEUESREQUEST = _descriptor.Descriptor(
  name='QueuesRequest',
  full_name='loadleveler_collector.QueuesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='loadleveler_collector.QueuesRequest.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo', full_name='loadleveler_collector.QueuesRequest.repo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='loadleveler_collector.QueuesRequest.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='loadleveler_collector.QueuesRequest.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='loadleveler_collector.QueuesRequest.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='loadleveler_collector.QueuesRequest.password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_style', full_name='loadleveler_collector.QueuesRequest.output_style', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_url', full_name='loadleveler_collector.QueuesRequest.post_url', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_encoding', full_name='loadleveler_collector.QueuesRequest.content_encoding', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='loadleveler_collector.QueuesRequest.verbose', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=430,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='loadleveler_collector.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='loadleveler_collector.Response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='loadleveler_collector.Response.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=474,
)

DESCRIPTOR.message_types_by_name['JobsRequest'] = _JOBSREQUEST
DESCRIPTOR.message_types_by_name['QueuesRequest'] = _QUEUESREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobsRequest = _reflection.GeneratedProtocolMessageType('JobsRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOBSREQUEST,
  __module__ = 'loadleveler_collector_pb2'
  # @@protoc_insertion_point(class_scope:loadleveler_collector.JobsRequest)
  ))
_sym_db.RegisterMessage(JobsRequest)

QueuesRequest = _reflection.GeneratedProtocolMessageType('QueuesRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUESREQUEST,
  __module__ = 'loadleveler_collector_pb2'
  # @@protoc_insertion_point(class_scope:loadleveler_collector.QueuesRequest)
  ))
_sym_db.RegisterMessage(QueuesRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'loadleveler_collector_pb2'
  # @@protoc_insertion_point(class_scope:loadleveler_collector.Response)
  ))
_sym_db.RegisterMessage(Response)



_LOADLEVELERCOLLECTOR = _descriptor.ServiceDescriptor(
  name='LoadLevelerCollector',
  full_name='loadleveler_collector.LoadLevelerCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=477,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectJobs',
    full_name='loadleveler_collector.LoadLevelerCollector.CollectJobs',
    index=0,
    containing_service=None,
    input_type=_JOBSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CollectQueues',
    full_name='loadleveler_collector.LoadLevelerCollector.CollectQueues',
    index=1,
    containing_service=None,
    input_type=_QUEUESREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADLEVELERCOLLECTOR)

DESCRIPTOR.services_by_name['LoadLevelerCollector'] = _LOADLEVELERCOLLECTOR

# @@protoc_insertion_point(module_scope)
