# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import slurm_collector_pb2 as slurm__collector__pb2


class SlurmCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectJobs = channel.unary_unary(
        '/slurm_collector.SlurmCollector/CollectJobs',
        request_serializer=slurm__collector__pb2.JobsRequest.SerializeToString,
        response_deserializer=slurm__collector__pb2.Response.FromString,
        )
    self.CollectQueues = channel.unary_unary(
        '/slurm_collector.SlurmCollector/CollectQueues',
        request_serializer=slurm__collector__pb2.QueuesRequest.SerializeToString,
        response_deserializer=slurm__collector__pb2.Response.FromString,
        )


class SlurmCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CollectJobs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectQueues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SlurmCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectJobs': grpc.unary_unary_rpc_method_handler(
          servicer.CollectJobs,
          request_deserializer=slurm__collector__pb2.JobsRequest.FromString,
          response_serializer=slurm__collector__pb2.Response.SerializeToString,
      ),
      'CollectQueues': grpc.unary_unary_rpc_method_handler(
          servicer.CollectQueues,
          request_deserializer=slurm__collector__pb2.QueuesRequest.FromString,
          response_serializer=slurm__collector__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'slurm_collector.SlurmCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
